language: php
matrix:
  include:
  - php: 7.3
  - php: 7.4
  - php: 7.4
    env: deps=low
  fast_finish: true
before_install:
- phpenv config-rm xdebug.ini || echo "XDebug is not enabled"
install:
- if [[ $deps = low ]]; then make update-min; else make install; fi
script:
- if [[ $deps = low ]]; then make test-min; else make test; fi
